import { CommonModule } from '@angular/common';
import { Component, OnInit, signal, computed } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { FormsModule } from '@angular/forms';
import { StockMovementService, ProductMovementDto, StockMovementType } from 'src/app/proxy/stock-movements';
import { ProductService, ProductDto } from 'src/app/proxy/products';
import { BranchService, BranchDto } from 'src/app/proxy/branches';
import { ProductTypeService, ProductTypeDto } from 'src/app/proxy/product-types';
import { ConfigStateService, CurrentUserDto } from '@abp/ng.core';
@Component({
  selector: 'app-stock-movement',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule],
  templateUrl: './stock-movement.html',
  styleUrls: ['./stock-movement.scss']
})
export class StockMovementComponent implements OnInit {
  loading = signal(false);
  rows = signal<ProductMovementDto[]>([]);
  totalCount = signal(0);
  filtersCollapsed = false;
  pageSize = signal<number>(10);
  pageIndex = signal<number>(0);
  sorting = signal<string>('MovementDate DESC, StockMovementNo DESC');
  currentUser: CurrentUserDto;
  products = signal<ProductDto[]>([]);
  productTypes = signal<ProductTypeDto[]>([]); // ✅
  branches = signal<BranchDto[]>([]);
  isAdmin: boolean;

  // Build options from numeric enum generated by ABP
  movementTypeOptions = Object.keys(StockMovementType)
    .filter(k => isNaN(Number(k)))
    .map(name => ({ value: (StockMovementType as any)[name] as number, label: name }));

  form = this.fb.group({
    branchId: [''],
    productId: [''],
    productTypeId: [''],         // ✅ use ID (Guid)
    stockMovementType: [''],     // '' | number (enum)
    dateFrom: [''],              // "YYYY-MM-DDTHH:mm"
    dateTo: [''],
    includeCancelled: [false]
  });

  visibleFrom = computed(() => this.totalCount() === 0 ? 0 : this.pageIndex() * this.pageSize() + 1);
  visibleTo = computed(() => Math.min(this.totalCount(), (this.pageIndex() + 1) * this.pageSize()));

  constructor(
    private fb: FormBuilder,
    private reports: StockMovementService,
    private productSvc: ProductService,
    private productTypeSvc: ProductTypeService, // ✅
    private branchSvc: BranchService,
    private config: ConfigStateService,
  ) { }

  ngOnInit(): void {
    this.currentUser = this.config.getOne('currentUser');
    this.isAdmin = this.currentUser.roles.includes('admin');
    this.loadLookups();
    this.search();
  }

  private loadLookups() {
    this.productSvc.getList({ maxResultCount: 1000 }).subscribe(r => this.products.set(r.items ?? []));
    this.productTypeSvc.getList({ maxResultCount: 1000 }).subscribe(r => this.productTypes.set(r.items ?? [])); // ✅
    if(this.isAdmin)
      this.branchSvc.getList({ maxResultCount: 1000 }).subscribe(r => this.branches.set(r.items ?? []));
  }
  movementTypeLabel(type: StockMovementType): string {
    switch (type) {
      case StockMovementType.Purchase: return 'Purchase (+)';
      case StockMovementType.Sale: return 'Sale (−)';
      case StockMovementType.AdjustmentPlus: return 'Adjustment (+)';
      case StockMovementType.AdjustmentMinus: return 'Adjustment (−)';
      default: return String(type);
    }
  }
  movementTypeClass(t: number): string {
    switch (t) {
      case 0: return 'chip chip-green';   // Purchase
      case 1: return 'chip chip-red';     // Sale
      case 2: return 'chip chip-blue';    // Adjustment (+)
      case 3: return 'chip chip-orange';  // Adjustment (−)
      default: return 'chip';
    }
  }

  search() {
    this.pageIndex.set(0);
    this.fetchPage();
  }

  fetchPage() {
    this.loading.set(true);
    const v = this.form.value;

    const typeFilter =
      v.stockMovementType === '' || v.stockMovementType === null || v.stockMovementType === undefined
        ? undefined
        : Number(v.stockMovementType);

    this.reports.getProductMovements({
      branchId: v.branchId || undefined,
      productId: v.productId || undefined,
      productTypeId: v.productTypeId || undefined, // ✅ pass ID
      stockMovementType: typeFilter,                // ✅ enum number
      dateFrom: v.dateFrom || undefined,           // full datetime
      dateTo: v.dateTo || undefined,
      includeCancelled: !!v.includeCancelled,
      skipCount: this.pageIndex() * this.pageSize(),
      maxResultCount: this.pageSize(),
      sorting: this.sorting()
    }).subscribe({
      next: res => {
        this.rows.set(res.items ?? []);
        this.totalCount.set(res.totalCount ?? 0);
      },
      error: () => this.loading.set(false),
      complete: () => this.loading.set(false)
    });
  }

  reset() {
    this.form.reset({
      includeCancelled: false,
      stockMovementType: '',
      productTypeId: ''
    });
    this.search();
  }

    changePage(delta: number) {
    const next = this.pageIndex() + delta;

    // Block going before first page
    if (next < 0) {
      return;
    }

    // Block going after last page
    if (delta > 0 && this.visibleTo() >= this.totalCount()) {
      return;
    }

    this.pageIndex.set(next);
    this.fetchPage();
  }


  changeSort(col: string) {
    const current = this.sorting().toLowerCase();
    const isSame = current.startsWith(col.toLowerCase());
    const next = isSame && current.includes('desc') ? `${col} ASC` : `${col} DESC`;
    this.sorting.set(next);
    this.search();
  }

  onPageSizeChange(raw: string | number) {
    const val = typeof raw === 'number' ? raw : parseInt(raw, 10);
    this.pageSize.set(isNaN(val) ? 25 : val);
    this.search();
  }

  trackRow = (_: number, r: ProductMovementDto) => r.id;
}
